theme: jekyll-theme-dinky
title: Reuben Feinman
avatar: https://github.com/rfeinman/rfeinman.github.io/blob/master/avatar.jpeg
description: Ph.D. student in Computional Neuroscience and New York University