theme: jekyll-theme-dinky
title: Reuben Feinman
avatar: https://github.com/rfeinman/rfeinman.github.io/blob/master/images/avatar.jpeg
description: Ph.D. Student at New York University
url: "https://rfeinman.github.io"